/**
 * SpaceRegistry — EAOIN 1.0 space expansion.
 *
 * Stars, planets, galaxies, anomalies, civilizations, etc.
 * Millions of procedural planets are generated by seed; we list a curated
 * sample here plus the catalog of star/galaxy types.
 */

export type StarClass = 'O' | 'B' | 'A' | 'F' | 'G' | 'K' | 'M' | 'Brown Dwarf' | 'White Dwarf' | 'Neutron Star' | 'Pulsar' | 'Black Hole' | 'Quasar' | 'Binary' | 'Variable' | 'Protostar';

export interface StarSystemDef {
  id: string;
  name: string;
  starClass: StarClass;
  planetCount: number;
  galaxy: string;
  distance: number; // light years
  discovered: boolean;
  colonized: boolean;
  hazards: string[];
  specialFeatures: string[];
}

export interface PlanetDef {
  id: string;
  name: string;
  system: string;
  type: 'terrestrial' | 'gas_giant' | 'ice' | 'lava' | 'ocean' | 'desert' | 'forest' | 'barren' | 'moon' | 'ringed' | 'dark' | 'crystal' | 'alien';
  size: number; // earth radii
  gravity: number; // G
  atmosphere: 'none' | 'thin' | 'normal' | 'thick' | 'toxic' | 'corrosive';
  temperature: number; // K
  habitability: number; // 0-1
  resources: string[];
  life: string[];
  anomalies: string[];
  procedurallyGenerated: boolean;
}

const STAR_SYSTEMS: StarSystemDef[] = [
  { id: 'sol', name: 'Sol', starClass: 'G', planetCount: 8, galaxy: 'Milky Way', distance: 0, discovered: true, colonized: true, hazards: [], specialFeatures: ['Habitable Zone', 'Asteroid Belt', 'Oort Cloud'] },
  { id: 'alpha_centauri', name: 'Alpha Centauri', starClass: 'Binary', planetCount: 3, galaxy: 'Milky Way', distance: 4.37, discovered: true, colonized: false, hazards: ['Binary Star Flares'], specialFeatures: ['Proxima Centauri b (Habitable)'] },
  { id: 'sirius', name: 'Sirius', starClass: 'Binary', planetCount: 0, galaxy: 'Milky Way', distance: 8.6, discovered: true, colonized: false, hazards: ['White Dwarf Radiation'], specialFeatures: ['Sirius A & B'] },
  { id: 'vega', name: 'Vega', starClass: 'A', planetCount: 5, galaxy: 'Milky Way', distance: 25, discovered: true, colonized: false, hazards: ['Debris Disk'], specialFeatures: ['Vegan Asteroid Belt'] },
  { id: 'betelgeuse', name: 'Betelgeuse', starClass: 'M', planetCount: 2, galaxy: 'Orion Arm', distance: 700, discovered: true, colonized: false, hazards: ['Supernova Imminent', 'Stellar Winds'], specialFeatures: ['Red Supergiant', 'Pre-Supernova'] },
  { id: 'crab_nebula', name: 'Crab Pulsar', starClass: 'Pulsar', planetCount: 0, galaxy: 'Orion Arm', distance: 6500, discovered: true, colonized: false, hazards: ['Pulsar Radiation'], specialFeatures: ['Nebula Remains'] },
  { id: 'sagittarius_a', name: 'Sagittarius A*', starClass: 'Black Hole', planetCount: 0, galaxy: 'Milky Way Core', distance: 26_000, discovered: true, colonized: false, hazards: ['Spaghettification', 'Time Dilation'], specialFeatures: ['Supermassive Black Hole', 'Event Horizon'] },
  { id: 'three_c_273', name: '3C 273', starClass: 'Quasar', planetCount: 0, galaxy: 'Virgo', distance: 2.4e9, discovered: true, colonized: false, hazards: ['Quasar Jets', 'X-Ray Burst'], specialFeatures: ['Active Galactic Nucleus', 'Relativistic Jet'] },
  { id: 'gliese_581', name: 'Gliese 581', starClass: 'M', planetCount: 6, galaxy: 'Milky Way', distance: 20.3, discovered: true, colonized: true, hazards: ['Tidal Lock'], specialFeatures: ['Habitable Zone', 'Gliese 581g (Habitable)'] },
  { id: 'trappist_1', name: 'TRAPPIST-1', starClass: 'M', planetCount: 7, galaxy: 'Milky Way', distance: 39, discovered: true, colonized: true, hazards: ['Stellar Flares'], specialFeatures: ['7 Earth-sized planets', 'Habitable Zone'] },
  { id: 'kepler_186', name: 'Kepler-186', starClass: 'M', planetCount: 5, galaxy: 'Milky Way', distance: 500, discovered: true, colonized: false, hazards: [], specialFeatures: ['Kepler-186f (Habitable)'] },
  { id: 'wolf_359', name: 'Wolf 359', starClass: 'M', planetCount: 2, galaxy: 'Milky Way', distance: 7.9, discovered: true, colonized: false, hazards: ['Flare Star'], specialFeatures: ['Battle of Wolf 359 Site'] },
  { id: 'andromeda_prime', name: 'Andromeda Prime', starClass: 'G', planetCount: 6, galaxy: 'Andromeda', distance: 2_537_000, discovered: true, colonized: true, hazards: ['Distant'], specialFeatures: ['Andromeda Galaxy Hub'] },
  { id: 'triangulum_central', name: 'Triangulum Hub', starClass: 'Black Hole', planetCount: 0, galaxy: 'Triangulum', distance: 2_730_000, discovered: true, colonized: false, hazards: ['Black Hole'], specialFeatures: ['Galactic Core'] },
  { id: 'whirlpool_a', name: 'Whirlpool A', starClass: 'G', planetCount: 4, galaxy: 'Whirlpool', distance: 23_000_000, discovered: true, colonized: false, hazards: ['Galactic Collision'], specialFeatures: ['Spiral Galaxy', 'Starburst'] },
  { id: 'sombrero_central', name: 'Sombrero Central', starClass: 'Black Hole', planetCount: 1, galaxy: 'Sombrero', distance: 29_300_000, discovered: true, colonized: false, hazards: ['Lenticular Galaxy'], specialFeatures: ['Supermassive Black Hole'] },
  { id: 'pinwheel_1', name: 'Pinwheel Sector 1', starClass: 'K', planetCount: 8, galaxy: 'Pinwheel', distance: 21_000_000, discovered: true, colonized: false, hazards: [], specialFeatures: ['Multiple Habitable Worlds'] },
  { id: 'cygnus_a', name: 'Cygnus A', starClass: 'Quasar', planetCount: 0, galaxy: 'Cygnus', distance: 600_000_000, discovered: true, colonized: false, hazards: ['Powerful Radio Jets'], specialFeatures: ['Brightest Radio Galaxy'] },
  { id: 'm87_central', name: 'M87*', starClass: 'Black Hole', planetCount: 0, galaxy: 'Virgo A', distance: 53_500_000, discovered: true, colonized: false, hazards: ['Supermassive BH', 'Relativistic Jet'], specialFeatures: ['First Photographed BH'] },
  { id: 'roque_25', name: 'Roque 25', starClass: 'Brown Dwarf', planetCount: 4, galaxy: 'Milky Way', distance: 12.7, discovered: true, colonized: false, hazards: ['Failed Star'], specialFeatures: ['Brown Dwarf'] },
];

const PLANETS: PlanetDef[] = [
  { id: 'mercury', name: 'Mercury', system: 'sol', type: 'barren', size: 0.38, gravity: 0.38, atmosphere: 'none', temperature: 440, habitability: 0, resources: ['Iron', 'Nickel'], life: [], anomalies: ['Cratered Surface'], procedurallyGenerated: false },
  { id: 'venus', name: 'Venus', system: 'sol', type: 'lava', size: 0.95, gravity: 0.91, atmosphere: 'thick', temperature: 737, habitability: 0, resources: ['Sulfuric Acid', 'CO2'], life: [], anomalies: ['Acid Rain', 'Runaway Greenhouse'], procedurallyGenerated: false },
  { id: 'earth', name: 'Earth', system: 'sol', type: 'ocean', size: 1.0, gravity: 1.0, atmosphere: 'normal', temperature: 288, habitability: 1.0, resources: ['Water', 'Iron', 'Coal', 'Oil', 'Uranium', 'Life'], life: ['Humans', 'Animals', 'Plants'], anomalies: [], procedurallyGenerated: false },
  { id: 'mars', name: 'Mars', system: 'sol', type: 'desert', size: 0.53, gravity: 0.38, atmosphere: 'thin', temperature: 210, habitability: 0.4, resources: ['Iron', 'Water Ice', 'Methane'], life: [], anomalies: ['Olympus Mons', 'Valles Marineris'], procedurallyGenerated: false },
  { id: 'jupiter', name: 'Jupiter', system: 'sol', type: 'gas_giant', size: 11.2, gravity: 2.53, atmosphere: 'thick', temperature: 165, habitability: 0, resources: ['Hydrogen', 'Helium'], life: [], anomalies: ['Great Red Spot', '79 Moons'], procedurallyGenerated: false },
  { id: 'saturn', name: 'Saturn', system: 'sol', type: 'gas_giant', size: 9.4, gravity: 1.07, atmosphere: 'thick', temperature: 134, habitability: 0, resources: ['Hydrogen', 'Helium', 'Ice Rings'], life: [], anomalies: ['Rings', 'Titan (Moon)'], procedurallyGenerated: false },
  { id: 'uranus', name: 'Uranus', system: 'sol', type: 'ice', size: 4.0, gravity: 0.89, atmosphere: 'thick', temperature: 76, habitability: 0, resources: ['Methane', 'Ice'], life: [], anomalies: ['Tilted 98°'], procedurallyGenerated: false },
  { id: 'neptune', name: 'Neptune', system: 'sol', type: 'ice', size: 3.9, gravity: 1.14, atmosphere: 'thick', temperature: 72, habitability: 0, resources: ['Methane', 'Ice'], life: [], anomalies: ['Great Dark Spot'], procedurallyGenerated: false },
  { id: 'proxima_b', name: 'Proxima b', system: 'alpha_centauri', type: 'terrestrial', size: 1.07, gravity: 1.1, atmosphere: 'normal', temperature: 234, habitability: 0.8, resources: ['Iron', 'Water'], life: ['Microbial?'], anomalies: ['Tidal Lock'], procedurallyGenerated: false },
  { id: 'trappist_1e', name: 'TRAPPIST-1e', system: 'trappist_1', type: 'ocean', size: 0.92, gravity: 0.93, atmosphere: 'normal', temperature: 251, habitability: 0.9, resources: ['Water', 'Iron'], life: ['Possibly'], anomalies: ['Tidal Lock'], procedurallyGenerated: false },
  { id: 'kepler_186f', name: 'Kepler-186f', system: 'kepler_186', type: 'terrestrial', size: 1.11, gravity: 1.1, atmosphere: 'normal', temperature: 188, habitability: 0.85, resources: ['Iron', 'Water'], life: ['Unknown'], anomalies: [], procedurallyGenerated: false },
  { id: 'andromeda_prime_world', name: 'New Andromeda', system: 'andromeda_prime', type: 'forest', size: 1.05, gravity: 1.0, atmosphere: 'normal', temperature: 290, habitability: 1.0, resources: ['Exotic Matter', 'Dark Energy'], life: ['Andromedans'], anomalies: ['Crystal Forests'], procedurallyGenerated: false },
  // Procedurally-discovered planets (auto-generated per seed)
];

export const ALL_STAR_SYSTEMS: StarSystemDef[] = STAR_SYSTEMS;
export const ALL_PLANETS: PlanetDef[] = PLANETS;

export function getStarSystem(id: string): StarSystemDef | undefined {
  return ALL_STAR_SYSTEMS.find((s) => s.id === id);
}

export function getPlanet(id: string): PlanetDef | undefined {
  return ALL_PLANETS.find((p) => p.id === id);
}

export function getPlanetsBySystem(systemId: string): PlanetDef[] {
  return ALL_PLANETS.filter((p) => p.system === systemId);
}

export interface StarDef {
  id: string;
  name: string;
  type: StarClass;
  mass: number;
  temperature: number;
  planets: string[];
}

export const STAR_CLASS_INFO: Record<StarClass, { color: string; temp: string; desc: string; size: string; lifespan: string }> = {
  'O': { color: '#9bb0ff', temp: '30,000+ K', desc: 'Massive blue star. Rare and short-lived.', size: '>16 solar masses', lifespan: '<10 Myr' },
  'B': { color: '#aabfff', temp: '10,000-30,000 K', desc: 'Hot blue-white star.', size: '2-16 solar masses', lifespan: '10-100 Myr' },
  'A': { color: '#cad7ff', temp: '7,500-10,000 K', desc: 'White star like Vega.', size: '1.4-2 solar masses', lifespan: '100 Myr-1 Gyr' },
  'F': { color: '#f8f7ff', temp: '6,000-7,500 K', desc: 'Yellow-white star.', size: '1.05-1.4 solar masses', lifespan: '1-3 Gyr' },
  'G': { color: '#fff4e8', temp: '5,200-6,000 K', desc: 'Yellow star like our Sun.', size: '0.8-1.05 solar masses', lifespan: '10 Gyr' },
  'K': { color: '#ffd2a1', temp: '3,700-5,200 K', desc: 'Orange dwarf.', size: '0.45-0.8 solar masses', lifespan: '15-30 Gyr' },
  'M': { color: '#ffcc6f', temp: '2,400-3,700 K', desc: 'Red dwarf. Most common star type.', size: '0.08-0.45 solar masses', lifespan: '>100 Gyr' },
  'Brown Dwarf': { color: '#a06a3a', temp: '500-2,400 K', desc: 'Failed star. Not quite massive enough for fusion.', size: '0.01-0.08 solar masses', lifespan: 'Infinite' },
  'White Dwarf': { color: '#ffffff', temp: '8,000-40,000 K', desc: 'Dead star remnant.', size: 'Earth-sized', lifespan: '10 Gyr' },
  'Neutron Star': { color: '#a8c8ff', temp: '600,000+ K', desc: 'Collapsed star. Teaspoon weighs a billion tons.', size: '~20 km diameter', lifespan: '10 Gyr' },
  'Pulsar': { color: '#5dd6ff', temp: '1,000,000+ K', desc: 'Spinning neutron star emitting beams.', size: '~20 km diameter', lifespan: '10 Myr-10 Gyr' },
  'Black Hole': { color: '#000000', temp: 'Near absolute zero', desc: 'Gravity so strong nothing escapes.', size: 'Point singularity', lifespan: '10^67 years' },
  'Quasar': { color: '#a879ff', temp: '10,000+ K', desc: 'Active galactic nucleus. Brighter than a galaxy.', size: 'Solar-system sized core', lifespan: '10-100 Myr' },
  'Binary': { color: '#ffd166', temp: 'Variable', desc: 'Two stars orbiting each other.', size: 'Two solar masses', lifespan: 'Variable' },
  'Variable': { color: '#ff6a3a', temp: 'Variable', desc: 'A star that changes brightness.', size: 'Variable', lifespan: 'Variable' },
  'Protostar': { color: '#a82a3a', temp: '2,300 K', desc: 'A star in the process of forming.', size: 'Sub-stellar to stellar', lifespan: 'Pre-main sequence' },
};

export const SPACE_ANOMALIES = [
  { id: 'roque_25', name: 'Roque 25', type: 'Brown Dwarf', desc: 'A rogue planet drifting through interstellar space.', effect: 'Cold damage' },
  { id: 'great_attractor', name: 'The Great Attractor', type: 'Gravity Anomaly', desc: 'A gravitational anomaly 250 million light-years away.', effect: 'Pulls ships off course' },
  { id: 'kessler_syndrome', name: 'Kessler Debris Field', type: 'Debris', desc: 'A dense field of space junk.', effect: 'Ship damage' },
  { id: 'space_whale', name: 'Space Whale Migration', type: 'Creature', desc: 'Massive space-faring creatures. Peaceful.', effect: 'None — beautiful' },
  { id: 'wormhole_zx', name: 'Wormhole ZX-7', type: 'Wormhole', desc: 'A stable wormhole to a distant galaxy.', effect: 'Fast travel unlocked' },
  { id: 'rogue_black_hole', name: 'Rogue Black Hole', type: 'Black Hole', desc: 'A wandering black hole, small but dangerous.', effect: 'Spaghettification' },
  { id: 'gamma_ray_burst', name: 'Gamma Ray Burst', type: 'GRB', desc: 'A burst of gamma radiation from a collapsing star.', effect: 'Radiation damage' },
  { id: 'neutron_star_quake', name: 'Neutron Star Quake', type: 'Starquake', desc: 'A massive quake on a neutron star surface.', effect: 'Gravitational waves' },
  { id: 'comet_swarm', name: 'Comet Swarm', type: 'Comets', desc: 'A swarm of icy comets passing through.', effect: 'Beautiful but dangerous' },
  { id: 'pulsar_signal', name: 'Pulsar Signal Beacon', type: 'Pulsar', desc: 'An artificial signal coming from a pulsar.', effect: 'Side quest triggered' },
  { id: 'dark_nebula', name: 'Dark Nebula', type: 'Nebula', desc: 'A cloud of dust blocking all light.', effect: 'Sensors disabled' },
  { id: 'space_pirate_station', name: 'Space Pirate Station', type: 'Outpost', desc: 'A station run by space pirates.', effect: 'Trade or fight' },
  { id: 'ancient_ruin_orbit', name: 'Ancient Ruins in Orbit', type: 'Ruins', desc: 'Orbital ruins of an ancient civilization.', effect: 'Loot and lore' },
  { id: 'lost_civilization_planet', name: 'Lost Civilization', type: 'Planet', desc: 'A planet with the ruins of an ancient race.', effect: 'Lore, loot' },
  { id: 'rare_resource_asteroid', name: 'Rare Asteroid', type: 'Asteroid', desc: 'An asteroid rich in rare materials.', effect: 'Mining opportunity' },
  { id: 'space_station_anomaly', name: 'Abandoned Station', type: 'Station', desc: 'A station with no crew. Why?', effect: 'Mystery' },
  { id: 'frozen_galaxy', name: 'Frozen Galaxy', type: 'Galaxy', desc: 'A galaxy where time moves slower.', effect: 'Aging' },
  { id: 'crystal_nebula', name: 'Crystal Nebula', type: 'Nebula', desc: 'A nebula made of living crystal.', effect: 'Beautiful' },
  { id: 'pirate_fleet', name: 'Pirate Fleet', type: 'NPC', desc: 'A fleet of pirate ships.', effect: 'Combat or trade' },
  { id: 'trading_outpost', name: 'Trading Outpost', type: 'Outpost', desc: 'A neutral station for traders.', effect: 'Shop' },
  { id: 'ancient_archive', name: 'Ancient Archive', type: 'Library', desc: 'An orbital library. Vast.', effect: 'Lore, quests' },
  { id: 'wormhole_network', name: 'Wormhole Network', type: 'Network', desc: 'A network of stable wormholes.', effect: 'Fast travel' },
  { id: 'binary_system', name: 'Binary Star System', type: 'Stars', desc: 'Two stars. Weird orbital patterns.', effect: 'Navigation hazard' },
  { id: 'pulsar_clock', name: 'Pulsar Clock', type: 'Pulsar', desc: 'A pulsar so regular it\'s used as a galactic clock.', effect: 'Time' },
  { id: 'quasar_beacon', name: 'Quasar Beacon', type: 'Quasar', desc: 'A quasar visible across the universe.', effect: 'Navigation' },
];

export const ALL_ANOMALIES = SPACE_ANOMALIES;
export const GALAXY_LIST = [
  { id: 'milky_way', name: 'Milky Way', type: 'Spiral', stars: '100-400 billion', planets: '~1 trillion+', colonized: true, description: 'Home galaxy.' },
  { id: 'andromeda', name: 'Andromeda', type: 'Spiral', stars: '~1 trillion', planets: '~10 trillion+', colonized: true, description: 'Closest major galaxy. On collision course with Milky Way.' },
  { id: 'triangulum', name: 'Triangulum', type: 'Spiral', stars: '40 billion', planets: '~100 billion+', colonized: true, description: 'Third largest in the Local Group.' },
  { id: 'whirlpool', name: 'Whirlpool', type: 'Spiral', stars: '~100 billion', planets: '~1 trillion+', colonized: false, description: 'Interacting with companion galaxy.' },
  { id: 'sombrero', name: 'Sombrero', type: 'Lenticular', stars: '~100 billion', planets: '~1 trillion+', colonized: false, description: 'Edge-on galaxy with prominent dust lane.' },
  { id: 'pinwheel', name: 'Pinwheel', type: 'Spiral', stars: '~1 trillion', planets: '~10 trillion+', colonized: true, description: 'Face-on spiral.' },
  { id: 'cygnus_a', name: 'Cygnus A', type: 'Elliptical', stars: '~10 trillion', planets: '~100 trillion+', colonized: false, description: 'Brightest radio galaxy.' },
  { id: 'virgo_a', name: 'Virgo A (M87)', type: 'Elliptical', stars: '~1 trillion', planets: '~10 trillion+', colonized: false, description: 'Hosts first photographed black hole.' },
  { id: 'large_magellanic', name: 'Large Magellanic Cloud', type: 'Dwarf Irregular', stars: '~30 billion', planets: '~30 billion+', colonized: true, description: 'Satellite galaxy of the Milky Way.' },
  { id: 'small_magellanic', name: 'Small Magellanic Cloud', type: 'Dwarf Irregular', stars: '~3 billion', planets: '~3 billion+', colonized: true, description: 'Companion to the LMC.' },
  { id: 'centaurus_a', name: 'Centaurus A', type: 'Lenticular', stars: '~100 billion', planets: '~1 trillion+', colonized: false, description: 'Active galactic nucleus.' },
  { id: 'ngc_1300', name: 'NGC 1300', type: 'Barred Spiral', stars: '~50 billion', planets: '~500 billion+', colonized: false, description: 'Classic barred spiral.' },
  { id: 'black_eye', name: 'Black Eye Galaxy', type: 'Spiral', stars: '~100 billion', planets: '~1 trillion+', colonized: false, description: 'Distinctive dark dust band.' },
  { id: 'cartwheel', name: 'Cartwheel', type: 'Ring', stars: '~50 billion', planets: '~500 billion+', colonized: false, description: 'A ring galaxy formed by collision.' },
  { id: 'antennae', name: 'Antennae', type: 'Interacting', stars: '~50 billion', planets: '~500 billion+', colonized: false, description: 'Two galaxies colliding.' },
  { id: 'phantom', name: 'Phantom Galaxy', type: 'Spiral', stars: '~100 billion', planets: '~1 trillion+', colonized: false, description: 'Beautiful face-on spiral.' },
];
